name: u_and_i
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/img/

  fonts:
    - family: parisienne # family 키에 폰트 이름을 지정할 수 있다
      fonts:
        - asset: asset/font/Parisienne-Regular.ttf # 등록할 폰트 파일의 위치

    - family: sunflower
      fonts:
        - asset: asset/font/Sunflower-Light.ttf
        - asset: asset/font/Sunflower-Medium.ttf
          weight: 500 # 폰트 두께
        - asset: asset/font/Sunflower-Bold.ttf
          weight: 700
